apiVersion: v1
kind: Secret
metadata:
  name: ekb-secret
  namespace: ekb
type: Opaque
data:
  # Base64 encoded values
  # DB_USERNAME=ekb_user
  DB_USERNAME: ZWtiX3VzZXI=
  # DB_PASSWORD=qwe123
  DB_PASSWORD: cXdlMTIz
  # JWT_SECRET=local-secret
  JWT_SECRET: bG9jYWwtc2VjcmV0
  # ARK_API_KEY=e54466ea-48d7-41f6-a190-6fb440e132dd
  ARK_API_KEY: ZTU0NDY2ZWEtNDhkNy00MWY2LWExOTAtNmZiNDQwZTEzMmRk
