global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth'
    metrics_path: /metrics
    static_configs:
      - targets: ['auth:8081']
  - job_name: 'document'
    metrics_path: /metrics
    static_configs:
      - targets: ['document:8082']
  - job_name: 'vector'
    metrics_path: /metrics
    static_configs:
      - targets: ['vector:8083']
  - job_name: 'query'
    metrics_path: /metrics
    static_configs:
      - targets: ['query:8084']
  - job_name: 'gateway'
    metrics_path: /metrics
    static_configs:
      - targets: ['gateway:8080']
